export const employmentTypes = [
  "None",
  "Casual",
  "Probationary",
  "Contractual",
  "Regular",
  "Job Order",
  "Permanent",
  "Temporary",
];

export const employmentStatuses = [
  "Wage-Employed",
  "Underemployed",
  "Self-Employed",
  "Unemployed",
];

export const educationalAttainments = [
  "No Grade Completed",
  "Elementary Undergraduate",
  "Elementary Graduate",
  "High School Undergraduate",
  "High School Graduate",
  "Junior High (K-12)",
  "Senior High (K-12)",
  "Post-Secondary Non-Tertiary/Technical Vocational Undergraduate",
  "Post-Secondary Non-Tertiary/Technical Vocational Graduate",
  "College Undergraduate",
  "College Graduate",
  "Masteral",
  "Doctorate",
];

export const clientClassifications = [
  "4Ps Beneficiary",
  "Displaced Worker",
  "Family Members of AFP and PNP Wounded in Action",
  "Industry Workers",
  "Out-Of-School Youth",
  "Rebel Returnees/Decommissioned Combatants",
  "TESDA Alumni",
  "Victim of Natural Disasters and Calamities",
  "Agrarian Reform Beneficiaries",
  "Drug Dependents Surenederers",
  "Farmers and Fishermen",
  "Inmates and Detainees",
  "Overseas Filipino Workers (OFW) Dependent",
  "Returning/Repatriated OFWs",
  "TVET Trainers",
  "Wounded-In-Action AFT and PNP Personnel",
  "Balik Probinsya",
  "Family Members of AFP and PNP Killed-in-Action",
  "MILF Beneficiary",
  "RCEF-RESP",
  "Student",
  "Uninformed Personnel",
  "Others",
];

export const disabilityTypes = [
  "Mental/Intellectual",
  "Hearing Disability",
  "Psychosocial Disability",
  "Visual Disability",
  "Disabiilty Due to Chronic Illness",
  "Orthopedic (Musculoskeletal) Disability",
  "Multiple Disabilities",
  "Learning Disability",
  "None",
];

export const disabilityCauses = [
  "Congenital/Inborn",
  "Illness",
  "Injury",
  "None",
];

export const civilStatues = [
  "Single",
  "Married",
  "Separated",
  "Divorced",
  "Annulled",
  "Widower",
  "Common Law/Live-in",
];

export const scholarTypes = ["TWSP", "PESFA", "STEP", "Others"];

export const registrationStatuses = [
  "Pending",
  "For Screening",
  "For Exam",
  "Enrolled",
];

export const municipalities = [
  "Botolan",
  "Cabangan",
  "Candelaria",
  "Castillejos",
  "Iba",
  "Masinloc",
  "Olongapo",
  "Palauig",
  "San Antonio",
  "San Felipe",
  "San Marcelino",
  "San Narciso",
  "Santa Cruz",
  "Subic",
];

export const provinces = [
  "Aurora",
  "Bataan",
  "Bulacan",
  "Nueva Ecija",
  "Pampanga",
  "Tarlac",
  "Zambales",
];

export const regions = [
  "National Capital Region (NCR)",
  "Cordillera Administrative Region (CAR)",
  "Ilocos Region (Region I)",
  "Cagayan Valley (Region II)",
  "Central Luzon (Region III)",
  "Calabarzon (Region IV-A)",
  "Mimaropa (Region IV-B)",
  "Bicol Region (Region V)",
  "Western Visayas (Region VI)",
  "Central Visayas (Region VII)",
  "Eastern Visayas (Region VIII)",
  "Zamboanga Peninsula (Region IX)",
  "Northern Mindanao (Region X)",
  "Davao Region (Region XI)",
  "Soccsksargen (Region XII)",
  "Caraga (Region XIII)",
  "Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)",
];

export const locationData = {
  "Central Luzon (Region III)": {
    Aurora: [
      "Baler",
      "Casiguran",
      "Dilasag",
      "Dinalungan",
      "Dingalan",
      "Dipaculao",
      "Maria Aurora",
      "San Luis",
    ],
    Bataan: [
      "Abucay",
      "Bagac",
      "Balanga",
      "Dinalupihan",
      "Hermosa",
      "Limay",
      "Mariveles",
      "Morong",
      "Orani",
      "Orion",
      "Pilar",
      "Samal",
    ],
    Bulacan: [
      "Angat",
      "Balagtas",
      "Baliuag",
      "Bocaue",
      "Bulakan",
      "Bustos",
      "Calumpit",
      "Guiguinto",
      "Hagonoy",
      "Malolos",
      "Marilao",
      "Meycauayan",
      "Norzagaray",
      "Obando",
      "Pandi",
      "Paombong",
      "Plaridel",
      "Pulilan",
      "San Ildefonso",
      "San Jose del Monte",
      "San Miguel",
      "San Rafael",
      "Santa Maria",
    ],
    "Nueva Ecija": [
      "Aliaga",
      "Bongabon",
      "Cabanatuan",
      "Cabiao",
      "Carranglan",
      "Cuyapo",
      "Gabaldon",
      "Gapan",
      "General Mamerto Natividad",
      "General Tinio",
      "Guimba",
      "Jaen",
      "Laur",
      "Licab",
      "Llanera",
      "Lupao",
      "Muñoz",
      "Nampicuan",
      "Palayan",
      "Pantabangan",
      "Peñaranda",
      "Quezon",
      "San Antonio",
      "San Isidro",
      "San Jose",
      "San Leonardo",
      "Santa Rosa",
      "Santo Domingo",
      "Talavera",
      "Talugtug",
      "Zaragoza",
    ],
    Pampanga: [
      "Angeles",
      "Apalit",
      "Arayat",
      "Bacolor",
      "Candaba",
      "Floridablanca",
      "Guagua",
      "Lubao",
      "Mabalacat",
      "Macabebe",
      "Magalang",
      "Masantol",
      "Mexico",
      "Minalin",
      "Porac",
      "San Fernando",
      "San Luis",
      "San Simon",
      "Santa Ana",
      "Santa Rita",
      "Santo Tomas",
      "Sasmuan",
    ],
    Tarlac: [
      "Anao",
      "Bamban",
      "Camiling",
      "Capas",
      "Concepcion",
      "Gerona",
      "La Paz",
      "Mayantoc",
      "Moncada",
      "Paniqui",
      "Pura",
      "Ramos",
      "San Clemente",
      "San Jose",
      "San Manuel",
      "Santa Ignacia",
      "Tarlac City",
      "Victoria",
    ],
    Zambales: [
      "Botolan",
      "Cabangan",
      "Candelaria",
      "Castillejos",
      "Iba",
      "Masinloc",
      "Olongapo",
      "Palauig",
      "San Antonio",
      "San Felipe",
      "San Marcelino",
      "San Narciso",
      "Santa Cruz",
      "Subic",
    ],
  },
};
